In [36]:
import cv2
import numpy as np

# Resize Rotate

In [14]:
# img = cv2.imread('brand.png')
# img = cv2.resize(img, (400, 400))
# img = cv2.resize(img, (0, 0), fx=0.5, fy=0.5)
# img = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
# cv2.imshow('Brand', img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
# print(img.shape)
# print(img)

(200, 200, 3)
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


# Video

In [15]:
cap = cv2.VideoCapture('DonaldBeanDeepfake.mp4')
fps = cap.get(cv2.CAP_PROP_FPS)
print(f'fps : {fps}')

while True:
    succes, frame = cap.read()
    if succes == False:
        cap.release()
        break
    width = int(cap.get(3))
    height = int(cap.get(4))
    
    image = np.zeros(frame.shape, np.uint8)
    smaller_frame = cv2.resize(frame, (0, 0), fx=0.5, fy=0.5)
    image[:height//2, :width//2] = smaller_frame
    image[height//2:, :width//2] = smaller_frame
    image[:height//2, width//2:] = smaller_frame
    image[height//2:, width//2:] = smaller_frame
    
    # image = cv2.line(image, (0, 0), (width, height), (255, 0, 0), 10)
    # image = cv2.line(image, (0, 0), (width, 0), (255, 0, 0), 10)
    # image = cv2.line(image, (0, 0), (0, height), (255, 0, 0), 10)
    # image = cv2.line(image, (0, height), (width, height), (255, 0, 0), 10)
    # image = cv2.line(image, (width, 0), (width, height), (255, 0, 0), 10)
    # image = cv2.line(image, (0, height//2), (width, height//2), (0, 255, 0), 10)
    # image = cv2.line(image, (width//2, 0), (width//2, height), (0, 255, 0), 10)
    image = cv2.rectangle(image, (0, 0), (width//2, height), (0, 255, 0), 10)
    image = cv2.circle(image, (width//2, height//2), 50, (0, 255, 0), -1)

    
    cv2.imshow('frame', image)
    if cv2.waitKey(int(fps)) == ord('m'):
        break

cap.release()
cv2.destroyAllWindows()

fps : 29.97002997002997


# putText

In [37]:
car_img = cv2.imread('car.jpg')
car_img = cv2.resize(car_img, (0, 0), fx=2, fy=2)
h, w, _ = car_img.shape
print(car_img.shape)
print(h)
print(w)

text = 'Coba Text'
font = cv2.FONT_HERSHEY_COMPLEX
font_sclale = 1.2
thickness = 3
text_size = cv2.getTextSize(text, font, font_sclale, thickness)[0]

w_text, h_text = text_size
print(h_text)
print(w_text)

text_X = int((w-w_text)/2)
text_Y = int((h+h_text)/2)

print(text_X)
print(text_Y)

text_img = cv2.putText(car_img, text, (text_X, text_Y), font, font_sclale, (0, 225, 0), thickness)

cv2.imshow('text_img', text_img)
if cv2.waitKey(0) == ord('m'):
    cv2.destroyAllWindows()

(336, 600, 3)
336
600
27
208
196
181


# Bitwise

In [39]:
img_bit = cv2.imread('bitwise.png')
img_bit = cv2.resize(img_bit, (0, 0), fx=2, fy=2)
print(img_bit.shape[:2])


# img_back = np.zeros(img_bit.shape, np.uint8)
img_back = cv2.imread('1bit1.png')
img_back = cv2.resize(img_back, (img_bit.shape[1], img_bit.shape[0]))
print(img_bit.shape)
print(img_back.shape)

bit_wise = cv2.bitwise_xor(img_bit, img_back, mask=None)
cv2.imshow('bitwise.png', bit_wise)
if cv2.waitKey(0) == ord('m'):
    cv2.destroyAllWindows()

(386, 524)
(386, 524, 3)
(386, 524, 3)


# Mask

In [35]:
# cek color from bgr in hsv
blue = np.uint8([[[255, 0,  0]]])
green = np.uint8([[[0, 255, 0]]])
red = np.uint8([[[0, 0, 255]]])

hsv_blue = cv2.cvtColor(blue, cv2.COLOR_BGR2HSV)
hsv_green = cv2.cvtColor(green, cv2.COLOR_BGR2HSV)
hsv_red = cv2.cvtColor(red, cv2.COLOR_BGR2HSV)

print(f'blue : {hsv_blue}')
print(f'green : {hsv_green}')
print(f'red : {hsv_red}')

blue : [[[120 255 255]]]
green : [[[ 60 255 255]]]
red : [[[  0 255 255]]]


In [ ]:
img_car = cv2.imread('car.jpg')
img_car = cv2.resize(img_car, (0, 0), fx=2, fy=2)

hsv_car = cv2.cvtColor(img_car, cv2.COLOR_BGR2HSV)

# pakai range antara ke bawah 10, ke atas 10 =>hue dicoba2
lowerb  = np.array([90, 0, 0])
upperb  = np.array([130, 255, 255])
masknya = cv2.inRange(hsv_car, lowerb, upperb)

bitwise_car = cv2.bitwise_and(img_car, img_car, mask= masknya)

# cv2.imshow('car', img_car)
# cv2.imshow('hsv_car', hsv_car)
cv2.imshow('bitwise_car', bitwise_car)


if cv2.waitKey(0) == ord('m'):
    cv2.destroyAllWindows()

# Edge detection

In [3]:
car = cv2.imread('car.jpg')
car_gray = cv2.cvtColor(car, cv2.COLOR_BGR2GRAY)
blurred_car = cv2.GaussianBlur(car, ksize=(3,5), sigmaX=0.5)
edge_car = cv2.Canny(blurred_car, 70, 135)
cv2.imshow('edge_car', edge_car)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Template Matching

In [46]:
brand = cv2.imread('brand.png')
brand_gray = cv2.cvtColor(brand, cv2.COLOR_BGR2GRAY)
ktm = cv2.imread('ktm.png', cv2.IMREAD_GRAYSCALE)
# ktm_gray = cv2.cvtColor(ktm, cv2.COLOR_BGR2GRAY)
match = cv2.matchTemplate(brand_gray, ktm, cv2.TM_CCOEFF_NORMED)

h, w = ktm.shape
loc = np.where(match>=0.95)#numpy where return tuple(row, column) == (y,x)
print(loc)
print(brand.shape)

for pcc in zip(*loc):
    print(f'pcc:{pcc}')
    print(f'pcc++:{(h+pcc[0], w+pcc[1])}')
    # cv2 rectangle use (x,y)
    cv2.rectangle(brand, pcc[::-1], (w+pcc[1]+5, h+pcc[0]+5), (0,0, 255), 4)
    # cv2.rectangle(brand, (9, 500), (2, 2), (0,0, 255), 4) 


cv2.imshow('brand', brand)
# # cv2.imshow('ktm', ktm)
# cv2.imshow('match', match)
cv2.waitKey(0)
cv2.destroyAllWindows()

(array([447, 447, 447], dtype=int64), array([671, 672, 673], dtype=int64))
(561, 1067, 3)
pcc:(447, 671)
pcc++:(510, 822)
pcc:(447, 672)
pcc++:(510, 823)
pcc:(447, 673)
pcc++:(510, 824)


In [45]:
l = [2, 3, 4, 5, 6, 7, 8]
s = slice(-1)
print(l[s])
print(l[-1])

[2, 3, 4, 5, 6, 7]
8
